### ISSUE TITLE
Replace most conditional compilation with the `libc crate`

### ISSUE THREAD

**Issue by niklasad1** [paritytech/parity-daemonize#16]
We could use the [libc crate](https://github.com/rust-lang/libc) instead re-inventing the wheel with our conditional compilation.

Also `libc` has renamed to some functions such as `_dup2` to `dup2` which makes it more convenient to use

However, it would require at least one conditional compilation check some like:

```rustc
#[cfg(feature = "std")]
extern crate libc;

#[cfg(feature = "std")]
pub use supported::foo;

#[cfg(not(feature = "std"))]
pub use unsupported::foo;
``` 

However, I'm not intimate familiar `Windows` and it might require to the `[WinApi](https://github.com/retep998/winapi-rs/tree/master)` if we do plan to implement.

**Comment by ordian** [comment]
Not sure what you're suggest to do, `libc` exposes different API depending on a platform, e.g. `libc::splice` is available only on linux.

**Comment by niklasad1** [comment]
Haha yeah, I don't know what I was thinking that doesn't work.
