### ISSUE TITLE
Why use `ErrorKind::Windows` instead of enforcing it at compile-time for `linux only`

### ISSUE THREAD

**Issue by niklasad1** [paritytech/parity-daemonize#4]
So, the crate has conditional compilation for `pub fn daemonize` for two cases:

- linux
- windows

We are resolving this at run-time rather than compile-time why?

Basically we could use `#![cfg(unix)` or `#![cfg(target_os = "linux")`?

I'm not sure exactly which platforms are targetted in this context should support this but I'm guessing only Linux?

**Comment by seunlanlege** [comment]
> We are resolving this at run-time rather than compile-time why?

not entirely sure what you mean, cfg is for conditional compilation. 

> Why use `ErrorKind::Windows` instead of enforcing it compile-time for `linux only`

this would prevent you from building cross-platform binaries

**Comment by niklasad1** [comment]
> not entirely sure what you mean, cfg is for conditional compilation.

Yes, but I mean why do we allow compilation at all for Windows? IMO, it doesn't even make sense make the compilation successful for Windows but no big deal if we keep it as it is. So now we are using conditional compilation to create a separate version that only returns `Error::Windows` for Windows

> this would prevent you from building cross-platform binaries

No, the cross-compiler will use the `cfg flags` for the architecture it tries to compile for. You can check it by: 

```$ rustc --target x86_64-pc-windows-gnu --print cfg```

**Comment by seunlanlege** [comment]
> Yes, but I mean why do we allow compilation at all for Windows

so we can add support for windows services in the near future

**Comment by niklasad1** [comment]
Ok, I see :+1:
